export const SOD_RULES = Object.freeze([
  Object.freeze({
    code: "gl.journal.create-post.same-record",
    recordType: "GL_JOURNAL",
    action_a: "gl.journal.create",
    action_b: "gl.journal.post",
    actorUserField: "createdByUserId",
    scope: "per-record",
    enforcement: "warn",
    reason:
      "SoD: manual journal creators should not post the same journal without separate review.",
  }),
  Object.freeze({
    code: "payments.batch.create-approve.same-record",
    recordType: "PAYMENT_BATCH",
    action_a: "payments.batch.create",
    action_b: "payments.batch.approve",
    actorUserField: "createdByUserId",
    scope: "per-record",
    enforcement: "block",
    reason: "Maker-checker: payment batch creators should not approve the same batch.",
  }),
  Object.freeze({
    code: "payroll.override.request-approve.same-record",
    recordType: "PAYROLL_MANUAL_SETTLEMENT_OVERRIDE",
    action_a: "payroll.settlement.override.request",
    action_b: "payroll.settlement.override.approve",
    actorUserField: "requestedByUserId",
    scope: "per-record",
    enforcement: "block",
    reason:
      "Maker-checker: manual settlement override requesters should not review the same request.",
  }),
  Object.freeze({
    code: "payroll.close.request-approve.same-record",
    recordType: "PAYROLL_PERIOD_CLOSE",
    action_a: "payroll.close.request",
    action_b: "payroll.close.approve",
    actorUserField: "requestedByUserId",
    scope: "per-record",
    enforcement: "block",
    reason: "Maker-checker: payroll close requesters should not approve-close the same period.",
  }),
  Object.freeze({
    code: "workflow.request-review.same-record",
    recordType: "WORKFLOW_INSTANCE",
    action_a: "workflow.instance.request",
    action_b: "workflow.instance.approve",
    actorUserField: "requestedByUserId",
    scope: "per-record",
    enforcement: "block",
    reason: "Maker-checker: workflow requesters should not approve their own workflow instance.",
  }),
  Object.freeze({
    code: "cari.request-review.same-record",
    recordType: "COUNTERPARTY_REQUEST",
    action_a: "cari.card.request",
    action_b: "cari.request.review",
    actorUserField: "requestedByUserId",
    scope: "per-record",
    enforcement: "block",
    reason: "Maker-checker: counterparty requesters should not review the same request.",
  }),
  Object.freeze({
    code: "local-close.reopen-review.same-record",
    recordType: "LOCAL_CLOSE_PACK_REOPEN_REQUEST",
    action_a: "ouclose.request_reopen",
    action_b: "local.close.reopen.review",
    actorUserField: "requestedByUserId",
    scope: "per-record",
    enforcement: "block",
    reason: "Maker-checker: reopen requesters should not review the same local close request.",
  }),
  Object.freeze({
    code: "inventory.transfer.initiate-approve.same-record",
    recordType: "INVENTORY_TRANSFER",
    action_a: "inventory.transfer.create",
    action_b: "inventory.transfer.approve",
    actorUserField: "initiatedByUserId",
    scope: "per-record",
    enforcement: "block",
    reason: "Maker-checker: inventory transfer initiators should not approve the same transfer.",
  }),
]);
